version: "3.9"

services:

  db:
    env_file: .env
    image: postgres:14-alpine
    container_name: db
    hostname: ${POSTGRES_HOST}
    volumes:
      - data_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    networks:
      - carshop-network

  api:
    build: .
    container_name: api
    command: >
        sh -c "python manage.py create_db
               python manage.py seed_db
               flask run"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - .:/app/
    links:
      - db:db
    ports:
      - "5000:5000"
    networks:
      - carshop-network
    depends_on:
      - db

volumes:
  data_db:

networks:
  carshop-network:
    driver: bridge